# Generated by Django 5.0.6 on 2025-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveloption',
            old_name='travel_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=10),
        ),
    ]
